# Generated by Django 3.1.4 on 2020-12-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('Bat', 'Batsman'), ('Bowl', 'Bowler'), ('Field', 'Fielder')], default='Bat', max_length=7)),
                ('batting_style', models.CharField(max_length=20)),
                ('bowling_style', models.CharField(max_length=20)),
                ('highest_score', models.IntegerField()),
                ('avg', models.FloatField()),
                ('economy', models.FloatField()),
                ('age', models.IntegerField()),
                ('nationality', models.CharField(max_length=15)),
            ],
        ),
    ]
