# Generated by Django 3.1.4 on 2020-12-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('nationality', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[('Batsman', 'Batsman'), ('Bowler', 'Bowler'), ('All-Rounder', 'All Rounder')], default='Batsman', max_length=12)),
                ('batting_style', models.CharField(max_length=20)),
                ('bowling_style', models.CharField(max_length=20)),
                ('total_matches', models.IntegerField(default=0)),
                ('total_runs', models.IntegerField(default=0)),
                ('highest_score', models.IntegerField(default=0)),
                ('best_bowling_figures', models.CharField(default='R/W', max_length=7)),
                ('avg', models.FloatField(default=0)),
                ('economy', models.FloatField(default=0)),
                ('five_wickets', models.IntegerField(default=0)),
                ('total_wickets', models.IntegerField(default=0)),
                ('fifties', models.IntegerField(default=0)),
                ('hundreds', models.IntegerField(default=0)),
            ],
        ),
    ]
